### ISSUE TITLE
Rip iPhone

### ISSUE THREAD

**Issue by TRIGGEREDNICK** [jakeajames/rootlessJB3#12]
Hi, thanks for this amazing tool but i've a problem...
I'm on iPhone X (A11) - iOS 12.1.1.

i've pressed "uninstall" on rootless.
**iTunes doesn't recognise my iPhone**
**App crashes once opened**, **no buttons working.** i can just move from my springboard and put my phone in standby.

i saw this thing one time, when the `/var/` folder get deleted.
Please help

My iPhone seems to be still jailbroken

![photo_2019-02-05_19-59-21](https://user-images.githubusercontent.com/16902168/52297527-3d735780-2981-11e9-8dfd-b9281c604512.jpg)

**Comment by jakeajames** [comment]
/var/ deleted? What? What did you install/do?

**Comment by TRIGGEREDNICK** [comment]
> 
> 
> /var/ deleted? What? What did you install/do?

The only thing i did was to inject a deb file, after some minutes i decided to uninstall the jailbreak with the button.

The last Rootless message was:
```
[*] Starting fun
[i] Kernel base: 0xfffffff010a04000
[i] uid: 0

[+] Escaped sandbox!
      Wrote file 0x1365245b8
[*] Uninstalling...
```

i can see i through the multitasking.

**Comment by TRIGGEREDNICK** [comment]
> 
> 
> /var/ deleted? What? What did you install/do?

i don't have deleted this folder, a friend did and the app was crashing once opened. 
I'm scared

**Comment by TRIGGEREDNICK** [comment]
I'm crying my iPhone has randomly rebooted. omg
