### ISSUE TITLE
need help, TweakInject can't compile

### ISSUE THREAD

**Issue by HuChundong** [jakeajames/rootlessJB3#142]
the make.sh file need update

make clean && make && ldid2 -S .theos/obj/debug/TweakInject.dylib && cd .theos/obj/debug/ &&tar -cvf ../../../../../bootstrap/bins/TweakInject.tar ./TweakInject.dylib

here is what i use to compile, after this,jailbreak stuck at [*] Installing app com.jakeashacks.iSuperSU

**Comment by HuChundong** [comment]
AMFI: '/private/var/containers/Bundle/tweaksupport/usr/lib/TweakInject.dylib' has no CMS blob?

update,if use make commond and replace the TweakInject.dylib, AMFI report this,so how to sign this dylib?

**Comment by jakeajames** [comment]
You need to inject it to trustcache or let the jailbreak do that once you rejailbreak
