### ISSUE TITLE
inoperability failure from cyberduck

### ISSUE THREAD

**Issue by p0sin** [jakeajames/rootlessJB3#18]
no idea why i get this, but im assuming its because of rootlessjb.... no idea..... any ideas?

**Comment by Hugario** [comment]
rootlessJB currently does not support SFTP (Secure File Transfer Protocol) via DropBear(?). SSH works fine, but SFTP will not. Cyberduck utilizes the SFTP protocol, so it won't (currently) be able to transfer files with an iPhone jailbroken with rootlessJB.

**Comment by resistor4u** [comment]
the workaround i've used is to install @tbodt's [iSH](https://github.com/tbodt/ish), add SSH/SFTP, then connect using @yourmachine.local or @whateverip. Doing so will allow you to `put` or `get` items to iSH's bundle container, and you can navigate to them in another shell, move them, `jtool` and `inject` them, etc.
