### ISSUE TITLE
Apps don't get reinjected after reboot.

### ISSUE THREAD

**Issue by person4268** [jakeajames/rootlessJB3#23]
All tweaks in /var/LIB/MobileSubstrate get injected into the trustcache after every jailbreak. But apps installed through the jailbreak aren't automatically injected into the trustcache, making me have to get the UUID of the app, and use ssh to make the app able to work.

**Comment by bluetr00p** [comment]
i will make iSuperSu working on my fork soon

**Comment by jakeajames** [comment]
Could you send logs of Xcode on the part where it trusts tweaksupport?

**Comment by person4268** [comment]
Do you mean in the device's console, or the rootlessJb app console?

**Comment by jakeajames** [comment]
Found issue, fix will come sometime soon
