### ISSUE TITLE
Doesn’t work on my iPod 6

### ISSUE THREAD

**Issue by punknugg666** [jakeajames/rootlessJB3#25]
Why doesn’t the jailbreak work on my iPod touch 6?? I tried everything from disabling find my iPhone to putting on Airplane mode and all it does is reboot my iPod. Is it not compatible with iPods?

**Comment by jakeajames** [comment]
Because it's not supported? Do you know what you're trying to install?

Il giorno giovedì 7 febbraio 2019, punknugg666 <notifications@github.com>
ha scritto:
