### ISSUE TITLE
Inject failing

### ISSUE THREAD

**Issue by nn9dev** [jakeajames/rootlessJB3#27]
I’m trying to use inject so I can run prefs for PencilChargingIndicator but every time I run ``cd /var/containers/Bundle/tweaksupport/Library/PreferenceBundles/PencilChargingIndicatorPreferences.bundle
inject PencilCharginIndicatorPreferences``
I get the error ``Unable to retrieve persisted port``. Running RootlessJB 3.2.x from Ignition and have iphone8,4 (SE)

**Comment by liudayu** [comment]
That's not how you run ``inject``...

<img width="918" alt="wechat5985e01562af3645f4fc955fa79a16d0" src="https://user-images.githubusercontent.com/8695302/52453253-28214780-2b92-11e9-90d7-6a4765f43962.png">

**Comment by nn9dev** [comment]
@liudayu that’s the thing, the thing I’m using it on IS an executable

**Comment by bluetr00p** [comment]
try running `inject /var/containers/Bundle/tweaksupport/Library/PreferenceBundles/PencilChargingIndicatorPreferences.bundle/PencilCharginIndicatorPreferences`

**Comment by nn9dev** [comment]
@bluetr00p did that and got the same error. Also made sure a number of times it was correctly written

**Comment by jakeajames** [comment]
You must run inject as root

Il giorno venerdì 8 febbraio 2019, nn9dev <notifications@github.com> ha
scritto:

**Comment by nn9dev** [comment]
@jakeajames it worked after logging in as root. might wanna add that. closing.
