### ISSUE TITLE
Tweaks not injecting after respring

### ISSUE THREAD

**Issue by TheRealKeto** [jakeajames/rootlessJB3#28]
When installing tweaks through Filza, respringing does not inject them. The only solution is to simply reboot and rejailbreak. 

Not sure what could be the cause but this only happens on iOS 12.1 and lower. 

Tested on both an iPhone SE and iPhone 8 with Ignition's RootlessJB

**Comment by liudayu** [comment]
You have to run ``inject path_to_file.dylib`` in ssh

**Comment by bluetr00p** [comment]
We don't have trust cache bypass so you need to run @liudayu s command or reboot
