### ISSUE TITLE
Dropbear Failing To Launch

### ISSUE THREAD

**Issue by M4cs** [jakeajames/rootlessJB3#3]
Device: iPhone8,1 N71AP
Version: 12.1.2

When running the jailbreak it escapes sandbox, installs the bootstrap, says "binaries already trusted?" and then fails to launch dropbear.

Steps taken to try and fix so far:

I have rebooted, uninstalled in rootlessJB, rebooted again, tried jailbreaking with tweaks on. Fails to launch dropbear. I repeat those steps but with tweaks off and it still fails to launch dropbear.

Compiled from source and sideloaded with Cydia Impactor. Could using Cydia Impactor be the issue?

**Comment by The3GamingStars** [comment]
yeah its impactors fault. It works fine with xcode on the same device

**Comment by M4cs** [comment]
@coreycusick how so?

**Comment by ShyamLad** [comment]
Gives me the same issue when I load through Apple Configurator as well :(

**Comment by coreycusick** [comment]
You will need this ipa and GeoFilza, and iZip, you will need to go into GeoFilza and go to /var/containers/bundle/Application/ find rootlessJB, click on it then /rootlessJB.app/ and click on the rootlessJB.zip, press the share button, then press iZip, unzip the files, then go back into GeoFilza, then navigate to /var/mobile/Containers/Data/Application/ then find iZip then go into documents then rootlessJB then rootlessJB.app, press edit, select tars and bins, and copy them, go to /var/containers/bundle/Application/, select rootlessJB, then go into rootlessJB.app and press paste, this will replace the corrupted(I'm assuming) files from Cydia Impactor with the correct not corrupted files, reboot the device, now it should be good to go
[Payload.ipa.zip](https://github.com/jakeajames/rootlessJB3/files/2830828/Payload.ipa.zip)

**Comment by M4cs** [comment]
Fixed by installing from ignition
