### ISSUE TITLE
Failed to copy kernelcache Iphone 7

### ISSUE THREAD

**Issue by Astrologies** [jakeajames/rootlessJB3#46]
offsets selected for iOS 12.0 or above
[*] copying to /var/mobile/Containers/Data/Application/0C365A66-4719-462C-88D0-1666779D8D6E/Documents/16.02.19:16.27.51_kernelcache
[-] Failed to copy kernelcache with error: The file “kernelcache” couldn’t be opened because you don’t have permission to view it.
	[i] Kernel base: 0xfffffff00da04000
[-] error on KernelRead(0x0000000000000000)
[-] error on KernelRead(0x00000000000000f8)
[-] error on KernelWrite(0x0000000000000028)
[-] error on KernelWrite(0x0000000000000030)
[-] error on KernelWrite(0x000000000000002c)
[-] error on KernelWrite(0x0000000000000034)
[-] error on KernelWrite(0x0000013815e0f328)
[-] error on KernelWrite(0x0000013815e0f32c)
[-] error on KernelWrite(0x0000013815e0f330)
[-] error on KernelWrite(0x0000013815e0f334)
[-] error on KernelWrite(0x0000013815e0f338)
[-] error on KernelWrite(0x0000013815e0f378)
[-] error on KernelWrite(0x0000013815e0f37c)
[-] error on KernelRead(0x0000000000000028)
[-] error on KernelRead(0x0000000000000000)
[-] error on KernelRead(0x00000000000000f8)
[-] error on KernelWrite(0x0000000000000028)
[-] error on KernelWrite(0x0000000000000030)
[-] error on KernelWrite(0x000000000000002c)
[-] error on KernelWrite(0x0000000000000034)
[-] error on KernelWrite(0x0000013815e0f328)
[-] error on KernelWrite(0x0000013815e0f32c)
[-] error on KernelWrite(0x0000013815e0f330)
[-] error on KernelWrite(0x0000013815e0f334)
[-] error on KernelWrite(0x0000013815e0f338)
[-] error on KernelWrite(0x0000013815e0f378)
[-] error on KernelWrite(0x0000013815e0f37c)
        [-] Failed to get root

**Comment by jakeajames** [comment]
fixed
