### ISSUE TITLE
fake_posix_spawn_common xpcproxy_blacklist useless

### ISSUE THREAD

**Issue by HuChundong** [jakeajames/rootlessJB3#49]
https://github.com/jakeajames/rootlessJB3/blob/5a79e873500621ac38f2a297271110dde8b00de4/rootlessJB/payloads_source/pspawn_payload/launchd_payload.m#L70

when the path is in blacklist, SBINJECT_PAYLOAD_DYLIB still inject into it

**Comment by HuChundong** [comment]
inject into powerlogHelperd case battery info always loading，and inject into  MobileBackupCacheDeleteService，syncdefaultsd，FileProvider.LocalStorage （maybe） case storge info always loading

maybe these libs should add into black_list

**Comment by jakeajames** [comment]
Damnit i'm an idiot 🤦‍♂️

**Comment by jakeajames** [comment]
Should be fixed now
