### ISSUE TITLE
Cydia Impactor Fix(with ipa)

### ISSUE THREAD

**Issue by coreycusick** [jakeajames/rootlessJB3#7]
You will need this ipa and GeoFilza, and iZip,Install the ipa for rootlessJB and Geofilza using Cydia Impactor and download iZip from the AppStore, you will then need to go into GeoFilza and go to /var/containers/bundle/Application/ find rootlessJB, click on it then /rootlessJB.app/ and click on the rootlessJB.zip, press the share button, then press iZip, unzip the files, then go back into GeoFilza, then navigate to /var/mobile/Containers/Data/Application/ then find iZip then go into documents then rootlessJB then rootlessJB.app, press edit, select tars and bins, and copy them, go to /var/containers/bundle/Application/, select rootlessJB, then go into rootlessJB.app and press paste, this will replace the corrupted(I'm assuming) files from Cydia Impactor with the correct not corrupted files, reboot the device, now it should be good to go, I'm not really sure if there is another way to do this...
[Payload.ipa.zip](https://github.com/jakeajames/rootlessJB3/files/2830828/Payload.ipa.zip)

Couldn't figure out how to use the pull request feature, so I just figured I'd put this here...Thanks

**Comment by coreycusick** [comment]
Moved to Pull Requests

**Comment by jakeajames** [comment]
Opening since I'm apparently wrong

**Comment by coreycusick** [comment]
Btw thanks for making such an amazing utility

**Comment by AmirRoohi2000** [comment]
ok lets see what happens, install iSuperUser as well or just tweaks?

**Comment by AmirRoohi2000** [comment]
will i followed your methode but still no tweaks
I went aheahd and installed cylinder and Zeppelin

**Comment by coreycusick** [comment]
Cylinder has to have something else done to it for it to work, zeppelin is something I’ve never used before, sometimes you have to uninstall from the app, reboot and reinstall, but you don’t have to redo the above only readd the tweaks, don’t replace any folders as that will remove some important things

https://docs.google.com/spreadsheets/u/1/d/19Qz9gbNQCr8QeeT5YWauPCBfoBsoL_SJCY5hpRlCIoE/htmlview#gid=0
That’s a link to a compatibility check

**Comment by AmirRoohi2000** [comment]
Oh yeah right forgot to do that, and ldid2 is not included with this jb right? But looking at the spreadsheet it shows that Zeppelin should work just after jailbreaking, but that is not the case. Thank you

**Comment by coreycusick** [comment]
No it is not, try the uninstall option, then rejailbreak, sometimes that will work, for me it was trial and error, but above is what I got to work, I’ll try Zeppelin later today and let you know if I can get it to work, I have videoHUD and home guesture right now

**Comment by AmirRoohi2000** [comment]
Nice thank you

**Comment by coreycusick** [comment]
@AmirRoohi2000 I tried Zeppelin, The settings is broken, even after manually signing it, but I was able to get it to half way work. Try patching the tweaks using ldid2. If you would like I could upload a copy of that but below is a patched copy of zeppelin to try, let me know if it works, thanks
[zep.zip](https://github.com/jakeajames/rootlessJB3/files/2833290/zep.zip)
